ALTER TABLE users
    ADD COLUMN IF NOT EXISTS street VARCHAR(150),
    ADD COLUMN IF NOT EXISTS city VARCHAR(150),
    ADD COLUMN IF NOT EXISTS state VARCHAR(150),
    ADD COLUMN IF NOT EXISTS pincode VARCHAR(10);
